name: Validate Branch Name on Pull Request

on:
    pull_request:
        branches:
            - main

jobs:
    validate-branch-name-pull-request:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Validate Branch Name on Pull Request
              run: |
                  BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
                  if [[ ! "$BRANCH_NAME" =~ ^(feature\/|fix\/|refactoring\/|testing\/) ]]; then
                    echo "Invalid branch name: $BRANCH_NAME"
                    echo "Branch name must start with 'feature/', 'fix/', 'refactoring/' or 'testing/'"
                    exit 1
                  fi
